name: AADL Notifier
on:
  schedule:
    - cron: "30 14 * * *"  # 10:30am ET OR 2.30 PM UTC
    - cron: "30 15 * * *"  # 11:30am ET
    - cron: "30 16 * * *"  # 12:30pm ET
    - cron: "30 17 * * *"  # 1:30pm ET
    - cron: "30 18 * * *"  # 2:30pm ET
    - cron: "30 19 * * *"  # 3:30pm ET
    - cron: "30 20 * * *"  # 4:30pm ET
    - cron: "30 21 * * *"  # 5:30pm ET
    - cron: "30 22 * * *"  # 6:30pm ET
    - cron: "30 23 * * *"  # 7:30pm ET
  workflow_dispatch:

jobs:
  check_aadl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4
      - name: Check AADL and send email
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          TO_EMAIL: ${{secrets.TO_EMAIL}}
        run: |
          python <<'EOF'
          import os, requests
          from bs4 import BeautifulSoup

          book_record = "10732671"
          catalog_base_url = "https://aadl.org/catalog/record/{}"
          full_url = catalog_base_url.format(book_record)
          r = requests.get(full_url)
          r.raise_for_status()
          if "<td>On Shelf</td>" in r.text:
              requests.post(
                  "https://api.resend.com/emails",
                  headers={"Authorization": f"Bearer {os.environ['RESEND_API_KEY']}"},
                  json={
                      "from": "AADL Notifier <on@resend.dev>",
                      "to": [{os.environ['TO_EMAIL']}],
                      "subject": "Book is on shelf!",
                      "html": f"Your book is now available."
                  }
              )
          EOF
